begin transaction

DROP TABLE PAT_TEST

SELECT ID, DOB, fac_Id, FNAME, LNAME, STATUS INTO [PAT_TEST] FROM PAT WHERE FAC_ID IN (SELECT ID FROM FAC WHERE DCODE IN ('2256'))

alter table PAT_TEST
add NEW_ID int


update PAT_TEST set new_id = (select max(PT2.ID) from PAT_TEST as PT2 where PAT_TEST.LNAME = PT2.Lname and pat_test.FNAME = pt2.fname and pat_test.DOB = pt2.DOB and pt2.STATUS = 'N') where status = 'N'
delete from PAT_test where new_id is null

delete from PAT_test where id = new_id

--select * from pat_test order by new_id
--select * from pat_par  inner join pat_test pt on ( pt.id = pat_par.pat_id ) left outer join pat_par pp_new on ( pt.new_id = pp_new.pat_id and pat_par.par_id = pp_new.par_id ) where pp_new.id is null and (pat_par.PAT_ID != 11590081 and pat_par.id != 130)

UPDATE RXF SET pat_ID = (SELECT NEW_id FROM pat_test WHERE pat_TEST.ID = RXF.pat_ID) where RXF.pat_ID IN (SELECT pat_TEST.ID FROM pat_TEST)
UPDATE RXF_ORD SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = RXF_ORD.PAT_ID) where RXF_ORD.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE pat_thp SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_THP.PAT_ID) where PAT_THP.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE CHL SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = CHL.PAT_ID) where CHL.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE INO SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = INO.PAT_ID) where INO.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PLC SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PLC.PAT_ID) where PLC.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE FIL SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = FIL.PAT_ID) where FIL.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE FIL_THP SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = FIL_THP.PAT_ID) where FIL_THP.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE VIS SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = VIS.PAT_ID) where VIS.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE ORD_QUE SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = ORD_QUE.PAT_ID) where ORD_QUE.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE FIL_QUE SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = FIL_QUE.PAT_ID) where FIL_QUE.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE TRF SET TO_PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = TRF.TO_PAT_ID) where TRF.TO_PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE TRF SET FROM_PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = TRF.FROM_PAT_ID) where TRF.FROM_PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_ALC SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_ALC.PAT_ID) where PAT_ALC.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE FIL_BIL SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = FIL_BIL.PAT_ID) where FIL_BIL.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE NFA SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = NFA.PAT_ID) where NFA.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_BOK SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_BOK.PAT_ID) where PAT_BOK.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_DIS SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_DIS.PAT_ID) where PAT_DIS.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
update pat_med set pat_id = pt.new_id from pat_med inner join pat_test pt on ( pt.id = pat_med.pat_id ) left outer join pat_med pt_new on ( pt.new_id = pat_med.pat_id and pat_med.MED_ID = pt_new.med_id ) where pt_new.id is null
UPDATE PAT_NHI SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_NHI.PAT_ID) where PAT_NHI.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_NM9 SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_NM9.PAT_ID) where PAT_NM9.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_NMC SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_NMC.PAT_ID) where PAT_NMC.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_NOT SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_NOT.PAT_ID) where PAT_NOT.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
update pat_par set pat_id = pt.new_id from pat_par  inner join pat_test pt on ( pt.id = pat_par.pat_id ) left outer join pat_par pp_new on ( pt.new_id = pp_new.pat_id and pat_par.par_id = pp_new.par_id ) where pp_new.id is null
UPDATE PAT_IMG SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_IMG.PAT_ID) where PAT_IMG.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PAT_PRO SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PAT_PRO.PAT_ID) where PAT_PRO.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PIN SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PIN.PAT_ID) where PIN.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE PNT SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = PNT.PAT_ID) where PNT.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE RXF_CON SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID = RXF_CON.PAT_ID) where RXF_CON.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)
UPDATE FAC_LOG SET PAT_ID = (SELECT NEW_id FROM PAT_test WHERE PAT_TEST.ID =FAC_LOG.PAT_ID) where FAC_LOG.PAT_ID IN (SELECT PAT_TEST.ID FROM PAT_TEST)

delete from PAT where PAT.id in (select PAT_test.id from PAT_test)

rollback